### ISSUE TITLE
Exclusion du partenaire ne marche pas

### ISSUE THREAD

**Issue by sebastien-roch** [Korko/SecretSanta#1]
Bonjour,
je viens de lancer un aléatoire pour Noël, et il semble que l'algorithme pour exclure un partenaire ne fonctionne pas de manière fiable, j'ai obtenu ma partenaire... dommage.
A vérifier si c'est l'algo ou l'input du formulaire côté JS qui a posé problème.
L'algorithme est-il testé? merci

**Comment by Korko** [comment]
Bonjour,
Merci du retour, c'est étrange mais bon je vais re-regarder. L'algorithme a été déjà testé depuis quelques années et pour le moment nous n'avons jamais eu de problèmes de ce côté. Je fouille et je reviens vers vous.
Merci.

**Comment by Korko** [comment]
Bonsoir,

J'ai trouvé d'où venait le problème : https://github.com/Korko/SecretSanta/commit/0e1424b8528eb9b2ab20f23bc6808cdf5740ef50

En effet, l'ancien système utilisait les positions des participants au lieu de leurs noms. Du coup forcément ça ne fonctionne pas. Mais l'aléatoire est bien testé pour gérer les partenaires comme il faut : https://github.com/Korko/SecretSanta/blob/master/tests/RandomizerTest.php

Je suis désolé pour le tirage buggué.

Merci

Korko

**Comment by sebastien-roch** [comment]
Merci!
