### ISSUE TITLE
Production not working anymore

### ISSUE THREAD

**Issue by cubitouch** [Korko/SecretSanta#20]
Hi there,

First, thank you very much for this app :)
I ran it successfully on Saturday but a phone number was incorrect. So I just tried to re-run it tonight and it seems there is a server error (from Chrome, around 10:45 PM). I tried 2-3 times but it doesn't work anymore.

Can you give it a look?

Thank you again,
Regards,
Hugo

**Comment by cubitouch** [comment]
PS : Mince, j'oubliais que je parlais à un dev français, l'habitude... :)

**Comment by Korko** [comment]
Oh salut ! Désolé je n'avais pas vu ton message. Je regarde rapidement.

**Comment by Korko** [comment]
Alors effectivement, le numéro de téléphone doit être sous la forme 0[6/7]12345678 et non +33[6/7]12345678 pour ce qui est des erreurs qui suivent, c'est un problème de token, tu as du garder la page ouverte trop longtemps. Faut que je fasse en sorte de gérer plus proprement cette erreur pour l'utilisateur (en gros refresh la page avec tout de re-rempli).

**Comment by cubitouch** [comment]
Super :) merci !

Le 20 déc. 2016 2:55 PM, "Jérémy Lemesle" <notifications@github.com> a
écrit :

**Comment by cubitouch** [comment]
Sauf erreur de ma part, je n'avais pas saisi en +336 mais bien en 06, je
referais un test ce soir...

Sinon sans rapport direct, tu es ouvert aux contributions sur le sujet
d'une app mobile ? :) Ça faciliterait grandement la saisie grâce aux
contacts du téléphone

Le 20 déc. 2016 3:36 PM, "Hugo Carnicelli" <hugocarnicelli@gmail.com> a
écrit :

**Comment by Korko** [comment]
Fais toi plaisir, je ne suis pas dev mobile et n'ai pas de smartphone mais je suis ouvert à toute contribution ;)

**Comment by cubitouch** [comment]
Dac, je regarderais si j'ai un peu de temps :)

Le 20 déc. 2016 3:44 PM, "Jérémy Lemesle" <notifications@github.com> a
écrit :

**Comment by cubitouch** [comment]
Je viens de relancer la machine, j'ai toujours un soucis.

J'ai fait un test avec 6 personnes, j'ai bien reçu les SMS.
J'ai refait un test avec les 16 personnes en condition réelles et ça ne passe pas.

J'ai toujours une erreur 500 lors de la première soumission et ensuite mon token n'est peut être plus valide comme tu le disais... Je vais refaire un test en sérialisant/désérialisant le formulaire en jQuery pour être plus rapide !

**Comment by cubitouch** [comment]
Test relancé en une vingtaine de secondes, toujours une erreur 500 :/

**Comment by Korko** [comment]
Alors le token n'est pas sensé être un problème, je l'ai désactivé, le recaptcha fait l'affaire. Mais en effet tu lèves des erreurs de timeout et de memory exception. Va falloir que je revois ça avec un plus grand nombre de participants pour mes tests. Si tu n'as que des exceptions simples (une personne à exclure), je peux te proposer une version précédente qui devrait fonctionner.

**Comment by cubitouch** [comment]
Oui, nous sommes tous en cadeau "séparé"

**Comment by cubitouch** [comment]
Je n'ai pas regardé en détail le fonctionnement de ton "aléatoire", mais ce qui prends du temps ne devrait être le "tirage" dans le chapeau, plutôt l'envoi des SMS/emails à première vue. Donc je suppose que l'envoi est géré pendant la boucle qui élimine un à un les participants restants. Je ne sais pas ce qu'il est possible de lancer en PHP comme asynchrone (je suis développeur .NET) mais sans stocker en mémoire ou autre, peut être qu'il est possible de lancer une liste de tâches dans le vent (potentiellement sans traiter le retour, puisque de toute manière l'interface n'est pas actuellement prévue pour attendre autrechose que "ok, c'est parti, il n'y a plus qu'à attendre")...

**Comment by Korko** [comment]
L'envoi de SMS/Email est super rapide, le plus dur c'est vraiment le "tirage" dans le chapeau en gérant toutes les exclusions possibles mais j'ai réduit drastiquement le calcul avec la 1.3.2 (que je viens de mettre en prod). ça devrait être ok. Pour la séparation des tâches via événements, c'est prévu mais je suis pas un grand fan.

**Comment by cubitouch** [comment]
C'est passé ce soir :) Merci beaucoup !

**Comment by Korko** [comment]
Oui j'a fais une modif assez drastique ce soir à l'algo d'aléatoire. Avec 7000 participants il met environ 20s. Je vais considérer que cela me convient xD

**Comment by cubitouch** [comment]
Oui, 7000 c'est pas mal même pour secret santa pro :D

2016-12-21 23:36 GMT+01:00 Jérémy Lemesle <notifications@github.com>:

**Comment by Korko** [comment]
Merci pour tous les retours et surtout pour ta patience, je ferme ce ticket de bug du coup ;)
Bon secret santa !

**Comment by cubitouch** [comment]
Avec plaisir, l'application est très utile ;)

2016-12-21 23:53 GMT+01:00 Jérémy Lemesle <notifications@github.com>:
